export const ADD_TODO = 'ADD_TODO';
export const DETAIL_TODO = 'DETAIL_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const UPDATE_TODO = 'UPDATE_TODO';
export const TOGGLE_TODO = 'TOGGLE_TODO';
export const ALL_REQUEST_TODO = 'ALL_TODO';
export const ALL_SUCCESS_TODO = 'ALL_SUCCESS_TODO';
export const ALL_FAILURE_TODO = 'ALL_FAILURE_TODO';
export const VISIBILITY_FILTERS = {
  SHOW_ALL: 'SHOW_ALL',
  SHOW_COMPLETED: 'SHOW_COMPLETED',
  SHOW_ACTIVE: 'SHOW_ACTIVE',
};

export const API_ERROR = 'API_ERROR';
export const AUTH_SUCCESS_AUTH = 'AUTH_SUCCESS_AUTH';
export const AUTH_FAILURE_AUTH = 'AUTH_FAILURE_AUTH';
export const AUTH_REQUEST_AUTH = 'AUTH_REQUEST_AUTH';
export const SUCCESS_AUTH = 'SUCCESS_AUTH';
export const ERROR_AUTH = 'ERROR_AUTH';
export const REGISTER_USER = 'REGISTER_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
